Add system test for supercell and incommensurate spinwave calc consistency
SpinW/spinw pull request #115
Opened 2022-11-18 16:29 UTC by RichardWaiteSTFC

DRAFT

Fixes #107

2022-11-21 13:52 UTC, mducle requested changes
Thansk @RichardWaiteSTFC for this test. So I think the number of modes check is not quite correct. The number of modes in a _commensurate_ calculation is `2 * n_atom * prod(nExt)` whilst that in an incommensurate calculation is `3 * 2 * n_atom * prod(nExt)`.

So for the `AF33kagome` case `n_atom=1`, but `prod(nExt) = 9` in the supercell whilst `prod(nExt)=1` for the incommensurate calculation. Thus there are 18 modes for the supercell but only 6 for the incommensurate and it is just by coincidence that the ratio here is `3`.

In the other two examples, `n_atom=2`, with `prod(nExt)=2` in the supercell and `prod(nExt)=1` in the incommensurate calculation, so there are 8 modes for the supercell and 12 modes in the incommensurate so there is no nice ratio.

The two sets of calculations are reconciled because the extra modes in the supercell calculations are "ghost modes" with zero intensity - hence looking at `swConv` is a good check. But we could also do a specific check, removing the ghost modes like:

```
    properties
        tol = 1e-5;
    end
    methods
        function om = remove_ghosts(testCase, spec)
            om = spec.omega(find(abs(spec.Sperp) > testCase.tol));
            om = sort(unique(round(om / testCase.tol) * testCase.tol));
        end
    end
    methods (Test)
        % main test code
        testCase.assertEqual(testCase.remove_ghosts(spec_super), testCase.remove_ghosts(spec_incom))
    end
```

2022-11-28 15:41 UTC, mducle approved these changes
Thanks this looks good. 

Just a note that in general, SpinW supports a simultaneous use of a supercell in "incommensurate" calculations - which occurs when `prod(nExt)>1` and `any(mod(k, 1)~=0)`. The interpretation is a bit weird and I not sure these calculations are strictly valid... but in this case the number of modes is `2 * prod(nExt) * 3 * n_matom`. The generated structure is the specified supercell which is _then_ propagated using `k`.

2022-12-08 15:07 UTC, rebeccafair reviewed
Maybe just add a line to the changelog to say a warning has been added to spinwave? Apart from that, looks good to me! Nice concise handling of the awkward ghost modes

2022-12-08 15:56 UTC, rebeccafair approved these changes

2022-12-08 16:51 UTC, merged