Test sw_egrid
SpinW/spinw pull request #130
Opened 2023-02-24 14:05 UTC by rebeccafair

2023-02-28 09:21 UTC, rebeccafair commented
As input I've used the 1D chain [qh 0 0] spectrum from the spinwave tests, though it might be nice to have a 2 magnetic atom system too, especially for testing the `modeIdx` argument. There seems to be a bug when `component` is `Px` or a fieldname (`fName`), unless I'm using them incorrectly! For now I've documented this behaviour in the `test_Px` and `test_fName_component` tests, checking that an error is raised.

There is a bit of inconsistent behaviour with the output structure where extra fields `Mab`, `Pab`, `intP` and some parameters are initialised when using the `Sperp` component, whereas they aren't initialised when a different component is used. This probably isn't a big deal, but this is why there are separate `sw_egrid_out_sperp` and `sw_egrid_out` test structs.

2023-02-28 14:53 UTC, RichardWaiteSTFC commented
> As input I've used the 1D chain [qh 0 0] spectrum from the spinwave tests, though it might be nice to have a 2 magnetic atom system too, especially for testing the `modeIdx` argument. There seems to be a bug when `component` is `Px` or a fieldname (`fName`), unless I'm using them incorrectly! For now I've documented this behaviour in the `test_Px` and `test_fName_component` tests, checking that an error is raised.

Thanks for documenting these, I think I'll try and address them in this PR

> There is a bit of inconsistent behaviour with the output structure where extra fields `Mab`, `Pab`, `intP` and some parameters are initialised when using the `Sperp` component, whereas they aren't initialised when a different component is used. This probably isn't a big deal, but this is why there are separate `sw_egrid_out_sperp` and `sw_egrid_out` test structs.

I wonder if that's because those fields ( `Mab`, `Pab`, `intP`) are in the output spectrum struct after running `sw_neutron`?

2023-02-28 15:04 UTC, RichardWaiteSTFC commented
Looks great, it's almost here thanks!
As a note to myself here are the things still to do:

- Test input parameters: `epsilon`, `autoEmin` and `imagChk`
- Test `modeIdx` with an example with two magnetic atoms
- passing a cell array of compoinents e.g. `'component',{'Sxx+Syy' 'Szz'}`

Is there anything else you think I've missed?

2023-04-21 13:21 UTC, RichardWaiteSTFC commented
In the failing test
`system_tests.systemtest_spinwave_incommensurate_and_supercell_consistency/test_AFM_kagome`
There are still some zero-energy modes that have the odd eigenvalue that is ~10^-3 (i.e. not quite zero) - which is getting to the limit where we don't want to neglect `DSF` from all eigenvalues below this threshold because valid modes may have such eigenvalues (e.g. near Gamma).
![image](https://user-images.githubusercontent.com/55979119/233644283-125f9f50-c474-42ce-a14e-cd18f5462071.png)
 I propose to filter out these modes 9or provide the user the option to do so) when calculating `swConv`  but it's a case of finding a code set of criteria. I can think of the following:

1.  Threshold fraction of eigenvalues <1e-6 (i.e. much smaller than typical resolution in data) ?
2. Such modes tend to have `DSF` with extremely large values ~10^7 (relative to e.g. median?)

Whatever approach we take we want to ensure we can discriminate between valid modes with v. small eigenvalues and won't mis-behave if few q-bins.

2023-07-03 08:13 UTC, mducle requested changes
I think we're almost there. The changes look good. I've just got a request to fix the `Px` bug. Regarding your comments about the zero energy boundary

> I propose to filter out these modes 9or provide the user the option to do so) when calculating swConv but it's a case of finding a code set of criteria. I can think of the following:
>
>    1. Threshold fraction of eigenvalues <1e-6 (i.e. much smaller than typical resolution in data) ?
>    2. Such modes tend to have DSF with extremely large values ~10^7 (relative to e.g. median?)
>
> Whatever approach we take we want to ensure we can discriminate between valid modes with v. small eigenvalues and won't  mis-behave if few q-bins.

I think option 2 is better - so maybe a check for eigenvalues below some threshold and with some intensity above some threshold?

> However, I'm not completely happy as it doesn't fix all the problems - there are still the following issues (that exist with the old code as well):
>
>   1. If imgChk=False then there is no guarantee that the ioMax < bin width so the first bin edge could be moved beyond the second
>   2. The energy bin edges are sorted, but this fails to account for the fact the first energy bin could be negative and span the elastic line (probably unlikely though)

Maybe if `imgChk=false` we don't move the bin edges at all?

Not sure what to do about the second issue... let's see if it becomes a big problem later...

2023-07-06 16:12 UTC, merged