Correct equations for q-range in sw_instrument
SpinW/spinw pull request #134
Opened 2023-03-24 14:35 UTC by mducle

Original author: J. R. Stewart (ISIS).

This was contributed by a user who found that the equations used in `sw_instrument` for the kinematic limits were incorrect. That is the equations were correct mathematically but does not actually represent what happens in instruments. Rather they assumed that the detectors extended from `thetamin` to `180-thetamin`. Instead all spectrometers have a much more limited range of scattering angles defined by `thetamin` and a `thetamax` which is signifcantly less than 180 degrees (around 135 degrees maximum for the largest spectrometers; around 60 degrees for smaller / high resolution spectrometers).

This PR corrects this.

----

To Test:

Run an example powder script (e.g. [tutorial 1](https://www.spinw.org/tutorials/01tutorial#7), [5](https://www.spinw.org/tutorials/05tutorial#5), or [6](https://www.spinw.org/tutorials/06tutorial#5)), and run it through `sw_instrument` and check that the kinematic limits look like those in [Mantid PyChop](https://docs.mantidproject.org/nightly/interfaces/direct/PyChop.html)

2023-05-11 09:33 UTC, RichardWaiteSTFC commented
@mducle - is this ready to test? It's been marked draft for a while

2023-05-11 10:21 UTC, mducle commented
@RichardWaiteSTFC ah yeah... I meant to write some tests for this but it dropped down the todo list and I forgot about it...

2023-06-26 10:24 UTC, RichardWaiteSTFC commented on swfiles/sw_instrument.m
>                  Emax = -(k0^2-(k0*cosT+sqrt(Q.^2-k0^2*sinT^2)).^2) * sw_converter(1,'k','meV');
This is nit-picking but can we not use `k0` - I think people will assume `k0` is $k_i$ (though I know it's obvious from the comment and the code) ! Can we just call in `kfix` or similar?

2023-06-26 10:27 UTC, RichardWaiteSTFC requested changes
Results agrees well with pychop - can you just add a release note and a doc string, thanks!

2023-06-26 10:27 UTC, RichardWaiteSTFC commented on swfiles/sw_instrument.m
> +inpForm.fname  = {'dE'    'ki'  'Ei'  'kf'  'Ef'  'plot' 'polDeg' 'thetaMin' 'thetaMax'};
Think the new parameter `thetaMax`  needs a do string well

2023-06-27 13:17 UTC, RichardWaiteSTFC approved these changes

2023-06-27 13:44 UTC, merged