Fix sw_issymspec to recognise powder spectra
SpinW/spinw pull request #146
Opened 2023-06-19 07:31 UTC by mducle

Quick fix for issue #145

2023-06-19 07:33 UTC, mducle commented
In future we should consider:

1. Converting the output spectra from a `struct` to a class with e.g. an `is_sym` property.
2. Add consistency tests which run through the tutorials and check that they work (even if it doesn't check their outputs for correctness).

2023-06-20 09:40 UTC, RichardWaiteSTFC requested changes
The fix looks good - perhaps we need to add this bug fix to the change log?

2023-06-20 09:49 UTC, RichardWaiteSTFC commented
> In future we should consider:
> 
> 1. Converting the output spectra from a `struct` to a class with e.g. an `is_sym` property.

I think it should definitely be a class - should `plotspec` be a method?

> 2. Add consistency tests which run through the tutorials and check that they work (even if it doesn't check their outputs for correctness).

I think we definitely need some form of doc-test like in mantid, but agreed just checking it doesn't error would be very helpful!
Is it as easy as running .m files in this directory (with exception of `publish_PSI.m`)
https://github.com/SpinW/spinw/tree/df2a40d47cfc24a3bddb4fef82ec10c179fdabdb/tutorials/publish

2023-06-27 15:11 UTC, RichardWaiteSTFC approved these changes

2023-06-27 15:14 UTC, merged