Minor Bugfixes
SpinW/spinw pull request #180
Opened 2024-04-25 18:14 UTC by mducle

A bunch of minor bugfixes which are either suggested by users or originally reported by them.

* Implement fixes suggested for `sw_plotspec` in #172
* Converts single q-point `hkl` to column to fix #179
* Remove inversion of user-inputed colormap in `sw_plotspec` to fix #131
* Refactor `sw_plotspec` to avoid recursive calls - split off main plotting stuff into an internal function which in order to fix #132
* Implement fixes suggested for `spinw.fitspec` in #98 
* Add spinw object to the spectrum object in `fitspec` to fix #158

2024-05-02 15:49 UTC, RichardWaiteSTFC commented
`sw_plotspec` errors on main branch when spinwave calculated using `fastmode=true` as doesn't have a copy the spinw object (I think because it turns on `fitmode` )
```
Unrecognized field name "obj".

Error in sw_plotspec (line 225)
unitL = spectra.obj.unit.label{1};
```
I haven't had a chance to tests this yet, but from a quick glance at the diff it looks like this may still be present - if so would it would make sense to fix it in this PR right?

2024-05-17 14:43 UTC, RichardWaiteSTFC commented
I have been able to reproduce #174 on master using this code adapted from tutorial 8
```
AF33kagome = spinw;
AF33kagome.genlattice('lat_const',[6 6 40],'angled',[90 90 120],'spgr','P -3');
AF33kagome.addatom('r',[1/2 0 0],'S', 1,'label','MCu1','color','r');
AF33kagome.gencoupling('maxDistance',7);
AF33kagome.addmatrix('label','J1','value',1.00,'color','g');
AF33kagome.addcoupling('mat','J1','bond',1);
S0 = [0 0 -1; 1 1 -1; 0 0 0];
AF33kagome.genmagstr('mode','helical','k',[-1/3 -1/3 0],...
    'n',[0 0 1],'unit','lu','S',S0,'nExt',[3 3 1]);

kag33Spec = AF33kagome.spinwave({[-1/2 0 0] [0 0 0] [1/2 1/2 0] 250},'hermit',false);

sw_plotspec(kag33Spec,'mode','auto','axLim',[0 2.5],'colorbar',false',...
    'colormap',[0 0 0],'imag',false,'sortMode',true,'dashed',true)
```
This is indeed fixed in this branch, but if you set `imag=true` it throws this error
```
Unrecognized function or variable 'modeList'.

Error in sw_plotspec>plotspec_internal (line 511)
                    hLegend(modeList+1) = hPlot(end);

Error in sw_plotspec (line 268)
        [fHandle0, pHandle0] = plotspec_internal(spectra, param);
```
which isn't thrown on main

2024-05-17 14:46 UTC, RichardWaiteSTFC commented
Running the code in #179 
```
FMchain = spinw;
FMchain.genlattice('lat_const',[3 8 8],'angled',[90 90 90])
FMchain.addatom('r', [0 0 0],'S', 1,'label','MCu1','color','blue')
FMchain.gencoupling('maxDistance',7)
FMchain.addmatrix('value',-eye(3),'label','Ja','color','green')
FMchain.addcoupling('mat','Ja','bond',1);
FMchain.genmagstr('mode','direct', 'k',[0 0 0],'n',[1 0 0],'S',[0; 1; 0]);
Q = sym([0 1 0]);
FMchain.spinwave(Q)
```
now throws a different error on this branch
```
Error using cell2mat
CELL2MAT does not support cell arrays containing cell arrays or objects.

Error in spinw/spinwave (line 480)
hkl    = cell2mat(hkl);
```
it still works for no symbolic

2024-05-17 14:57 UTC, mducle commented
Thanks @RichardWaiteSTFC - I'll try to fix these issues and do better testing! Will push something next week...

2024-05-17 15:07 UTC, RichardWaiteSTFC commented
> Thanks @RichardWaiteSTFC - I'll try to fix these issues and do better testing! Will push something next week...

No worries, I can also help out next week - I'll keep testing and post more comments if I find anything...

2024-05-17 15:13 UTC, RichardWaiteSTFC commented
Running tutorial 8 code again (see https://github.com/SpinW/spinw/pull/180#issuecomment-2117764803) with this plotting command
```
sw_plotspec(kag33Spec,'mode','auto','axLim',[0 2.5],'colorbar',false',...
    'colormap',[0 0 0],'sortMode',true,'dashed',true)
```
now throws this error 
```
Error using sw_plotspec>plotspec_internal
The dimensions of the colormap should be [3 nPlot]

Error in sw_plotspec (line 241)
        [fHandle0, pHandle0] = plotspec_internal(spectra, param);
```
 However if you convert the colormap to a column vector - i.e. `[0,0,0]'` - it works as expected and changes the colormap to greyscale (which was previously ignored on main branch).

Basically I think this is because you fixed #132 - but it does indicate that at one point it was possible to pass a row vector here?

2024-05-17 15:17 UTC, RichardWaiteSTFC commented
I was looking into testing #131 - it looks to me like jet is inverted (normally red is high and blue is low?)
Also this may not be due to your change but I think we should probably set 0 to white 
```
sw_plotspec(kag33Spec,'mode','auto','axLim',[0 2.5],'colorbar',false',...
    'colormap',@jet,'sortMode',true,'dashed',true) % [0 0 0]
```
![image](https://github.com/SpinW/spinw/assets/55979119/9be96996-a652-443c-a3f3-0bb018b35522)

2024-05-17 15:25 UTC, RichardWaiteSTFC requested changes
Thanks for this Duc, the `sw_plotspec` code looks much simpler to follow! And thanks for adding a test for `sw_fitspec`! Just a few small things above, I can also look into these next week I know you're busy!

2024-05-19 21:34 UTC, mducle commented
@RichardWaiteSTFC Thanks for the review - I think I fixed most issues raised...

> Also [472e474](https://github.com/SpinW/spinw/pull/180/commits/472e474c7af47a63135eebf61936c48b91562a40) needs to removed.

I think if we squash and merge, git is smart enough not to merge this twice, so it should be ok.

2024-05-20 14:52 UTC, RichardWaiteSTFC approved these changes
Looks good thanks - thanks also for updating the changelog!

2024-05-20 15:01 UTC, merged