Refactor simplex to use wrapper class handling bound and fixed parameters
SpinW/spinw pull request #204
Opened 2024-09-16 15:25 UTC by RichardWaiteSTFC

Refactor simplex to use wrapper class `ndbase.cost_function_wrapper` handling bound and fixed parameters.
Bound parameters are transformed using the formulation in MINUIT, as documented in lmfit 
https://lmfit.github.io/lmfit-py/bounds.html
The wrapper class works by storing the fixed parameters (if any) and returning all non-fixed (potentially transformed) parameters  that are used to evaluate the cost function so that an unconstrained minimisation can be performed (the fixed parameters are used internally when evaluating the cost function, but are not seen by the minimiser).

Have also added unit tests for wrapper class and simplex minimiser - it is setup to allow the unit test to be applied for any `ndbase` minimiser - however none of the other minimisers suceed in optimizing the problems in the test file.
- The `lm', `lm2` and `lm3` minimisers to not converge on the minimum (there's only one minimum in the cost function surface)
- The `pso` minimiser is not suited to unconstrained minimisation (generates initial particla swarm lcoations based on bounds - the default bounds are huge and don't depend on the input parameters).

Because the `lm` minimisers have been observed to perform poorly it has been decided to re-write them from scratch in a separate PR (after which hopefully they can share the same unit test as `simplex`)

2024-10-09 12:42 UTC, mducle requested changes
Looks good... just had a few comments, and one change to the `cost_function_wrapper` docstring.

Also, could you change the `build_pyspinw.yml` file to change `build` to `wheelhouse` in lines 164 and 171 (so the path reads `wheelhouse/*whl` instead of `build/*whl`)? It seems to be causing the python tests to fail... I don't know why it passed when I was doing the PR but is failing now... 🤷

2024-10-10 09:14 UTC, RichardWaiteSTFC commented on +sw_tests/+unit_tests/unittest_ndbase_cost_function_wrapper.m
> +            cost_val = cost_func_wrap.eval_cost_function(pfree);
That's right, I will definitely add a comment to say about the variable names in lmfit.

I found the `p_internal` name a bit confusing - as the free parameters are the ones that are actually optimised externally - they are passed from the optimiser to the cost function evaluation (and it is the bounded parameters that are used internally). At least to my mind!

2024-10-10 09:16 UTC, RichardWaiteSTFC commented on swfiles/+ndbase/cost_function_wrapper.m
> +                    if abs(ub(ipar) - lb(ipar)) < max(abs(ub(ipar)), 1)*1e-10
I'll make it as a static property, users may want to tweak it you never know!
I also wondered about letting the user pass in a boolean vector for which parameters should be fixed?

2024-10-10 09:27 UTC, RichardWaiteSTFC commented on swfiles/+ndbase/cost_function_wrapper.m
> +            pars_bound(obj.ifixed) = obj.pars_fixed;
I think the performance hit of calling `@(p) p` on every parameters is pretty low but even so I agree it is a bit wasteful - done mostly to keep the code the same for all parameters. I'll have a go!

2024-10-10 09:54 UTC, mducle commented on +sw_tests/+unit_tests/unittest_ndbase_cost_function_wrapper.m
> +            cost_val = cost_func_wrap.eval_cost_function(pfree);
Ok, sure let's keep the parameter `pfree` but add a comment about what it's called in lmfit/MINUIT and link to the docs there...

2024-10-10 09:58 UTC, mducle commented on swfiles/+ndbase/cost_function_wrapper.m
> +                    if abs(ub(ipar) - lb(ipar)) < max(abs(ub(ipar)), 1)*1e-10
> I also wondered about letting the user pass in a boolean vector for which parameters should be fixed?

That's how the `spec1d` [fitting program](https://www.mathworks.com/matlabcentral/fileexchange/1440-spec1d) (from which `lm3` was originally taken, via Horace) and Horace does it so some users will be familiar with that method. So, if it's not too much effort to add this as another option to fix parameters then that would be good to have.

2024-10-21 09:35 UTC, mducle approved these changes
Looks good. The failing test is because it uses the self-hosted runner on my desktop which is off as I was on holiday... I'm not going to be in until tomorrow to turn it on.

2024-10-24 10:21 UTC, mducle approved these changes

2024-11-01 16:16 UTC, merged